---
#file: roles/orange/tasks/setup.yml
- name: Make node group
  group: name=node system=yes state=present

- name: Make node user
  user: name=node group=node system=yes state=present

- name: Make Orange folder
  command: mkdir -p "/var/www/orange"

- name: Make docs folder
  command: mkdir -p "/var/www/orange/docs"

- name: Make shared folder
  command: mkdir -p "/var/www/orange/shared"

- name:  Install grunt CLI tools
  sudo: yes
  command: npm install -g grunt-cli

- name: Install zeromq
  yum: name={{ item }} state="latest"
  sudo: yes
  with_items:
   - zeromq
   - zeromq-devel

- name: Install python package dependencies
  yum: name={{ item }} state="latest"
  sudo: yes
  with_items:
   - python-pip
   - python-devel

- name:  Install node-gyp
  sudo: yes
  command: npm install -g node-gyp

- name: Install PM2
  sudo: yes
  command: npm install -g pm2 --unsafe-perm

